name: Deploy

on:
  push:
    branches:
      - main

jobs:
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook - Notify Start Deploy
        uses: tsickert/discord-webhook@v5.3.0
        continue-on-error: true
        with:
          webhook-url: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
          embed-author-name: "⬇️ Wiki | Mirasaki Development"
          embed-color: 14228765
          embed-description: "⌛ Deploying **`@${{ github.repository }}`**...\n📤 Service at <https://wiki.mirasaki.dev> is now temporarily unavailable."
  deploy:
    needs: notify-start
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/mirasaki-knowledge-base

            pm2 stop wiki-mirasaki-dev
            rm -rf .next
            git pull origin main
            npm ci
            npm run build

            pm2 restart wiki-mirasaki-dev
  notify-finish:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook - Notify Finish Deploy
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
          embed-author-name: "⬆️ Wiki | Mirasaki Development"
          embed-color: 45317
          embed-description: "✅ Finished deploying **`@${{ github.repository }}`**\n📥 [Service](https://wiki.mirasaki.dev) is back online"